
import React, { useEffect, useRef, useState, useMemo, useCallback } from 'react';
import mermaid from 'mermaid';

interface DiagramProps {
  chart: string;
  isDarkMode?: boolean;
}

type DiagramTheme = 'indiglo' | 'blueprint' | 'emerald' | 'rose';

mermaid.initialize({
  startOnLoad: false,
  securityLevel: 'loose',
  fontFamily: '"Inter", sans-serif',
  flowchart: {
    useMaxWidth: true,
    htmlLabels: true,
    curve: 'monotoneY'
  }
});

const Diagram: React.FC<DiagramProps> = ({ chart, isDarkMode: appDarkMode }) => {
  const containerRef = useRef<HTMLDivElement>(null);
  const [svg, setSvg] = useState<string>('');
  const [error, setError] = useState<{title: string, detail: string} | null>(null);
  const [isZoomed, setIsZoomed] = useState(false);
  const [isRendering, setIsRendering] = useState(true);
  const [transform, setTransform] = useState({ scale: 1, x: 0, y: 0 });
  const [activeTheme, setActiveTheme] = useState<DiagramTheme>('indiglo');

  const effectiveDarkMode = useMemo(() => {
    return appDarkMode ?? (window.matchMedia && window.matchMedia('(prefers-color-scheme: dark)').matches);
  }, [appDarkMode]);

  const handleReset = useCallback(() => setTransform({ scale: 1, x: 0, y: 0 }), []);

  const sanitizeMermaid = (raw: string): string => {
    // 1. Basic cleanup
    let processed = raw.replace(/```mermaid\n?|```/g, '').trim();
    
    // 2. Fix broken arrow syntax often generated by LLMs
    processed = processed
      .replace(/--\s*>/g, '-->') // Fix "-- >"
      .replace(/-\s*->/g, '-->') // Fix "- ->"
      .replace(/=\s*=>/g, '==>') // Fix "= =>"
      .replace(/-\s*\.\s*->/g, '-.->'); // Fix "- . ->"

    // 3. Force newline after header keywords if missing
    // Matches flowchart/graph followed by direction (TD, LR, etc) and then immediately a non-whitespace char
    processed = processed.replace(/^(flowchart|graph)\s+(TD|LR|BT|RL)([^\s\n])/i, '$1 $2\n$3');

    let lines = processed.split('\n');

    // 4. Ensure header exists
    if (lines.length > 0 && !lines[0].match(/^(graph|flowchart|sequenceDiagram|classDiagram|stateDiagram|erDiagram|gantt|pie|gitGraph)/i)) {
      lines.unshift('flowchart TD');
    }

    // 5. Wrap labels in quotes if they aren't already
    const finalLines = lines.map(line => {
      let l = line.trim();
      if (!l || l.startsWith('%%') || l.match(/^(graph|flowchart|sequenceDiagram)/i)) return l;
      
      // Handle nodes: ID[Label], ID(Label), ID((Label)), etc.
      // This regex attempts to find node definitions and ensure the label part is quoted.
      return l.replace(/([a-zA-Z0-9_.\-]+)\s*([\[\(\{]{1,2})(.*?)([\]\)\}]{1,2})/g, (match, id, open, label, close) => {
        let cleanLabel = label.trim();
        if (cleanLabel && !cleanLabel.startsWith('"')) {
          cleanLabel = `"${cleanLabel.replace(/"/g, "'")}"`;
        }
        return `${id}${open}${cleanLabel}${close}`;
      });
    });

    return finalLines.join('\n');
  };

  useEffect(() => {
    let active = true;
    const renderDiagram = async () => {
      if (!chart.trim()) {
        if (active) setIsRendering(false);
        return;
      }
      if (active) setIsRendering(true);
      try {
        const id = `mermaid-${Math.random().toString(36).substr(2, 9)}`;
        const cleanChart = sanitizeMermaid(chart);
        const { svg: renderedSvg } = await mermaid.render(id, cleanChart);
        if (active) {
          setSvg(renderedSvg);
          setError(null);
          setIsRendering(false);
        }
      } catch (err) {
        console.error('Mermaid rendering error:', err);
        if (active) {
          setError({ title: 'Mapping Conflict', detail: 'Visual logic synthesis failed. Displaying raw data.' });
          setIsRendering(false);
        }
      }
    };
    renderDiagram();
    return () => { active = false; };
  }, [chart, effectiveDarkMode, activeTheme]);

  if (error) {
    return (
      <div className="my-8 p-6 bg-slate-50 dark:bg-slate-900 rounded-3xl border border-dashed border-slate-300">
        <p className="text-[10px] font-black uppercase text-slate-400 mb-2">{error.title}</p>
        <pre className="text-[11px] font-mono text-slate-500 overflow-x-auto p-4 bg-white dark:bg-slate-800 rounded-xl">{chart}</pre>
      </div>
    );
  }

  return (
    <div className="my-10 relative group">
      <div className={`relative z-10 rounded-[2.5rem] border border-slate-200 dark:border-slate-800 shadow-xl overflow-hidden flex flex-col items-center justify-center p-8 min-h-[300px] ${effectiveDarkMode ? 'bg-slate-900' : 'bg-white'}`}>
        {isRendering ? (
          <div className="animate-pulse flex flex-col items-center">
            <div className="h-10 w-10 bg-indigo-500/20 rounded-full mb-4"></div>
            <p className="text-[10px] font-black uppercase text-indigo-500">Mapping...</p>
          </div>
        ) : (
          <div className="mermaid-container w-full flex justify-center overflow-x-auto" dangerouslySetInnerHTML={{ __html: svg }} />
        )}
      </div>
    </div>
  );
};

export default Diagram;
